const express = require("express");
const router = express.Router();
const regBrunvaController = require("../controllers/regBrunva.controller");
const payGenderController = require("../controllers/payGender.controller");
const valAddedController = require("../controllers/valAdded.controller");
const munBrunvaController = require("../controllers/munBrunva.controller");
const munValAddedController = require("../controllers/munValAdded.controller");
const munPayGenderController = require("../controllers/munPayGender.controller");
const regEmployeesController = require("../controllers/regEmployees.controller");
const munEmployeesController = require("../controllers/munEmployees.controller");
const regEmployedController = require("../controllers/regEmployed.controller");
const munEmployedController = require("../controllers/munEmployed.controller");
const regResaleController = require("../controllers/regResale.controller");
const munResaleController = require("../controllers/munResale.controller");
const regInvestmentController = require("../controllers/regInvestment.controller");
const munInvestmentController = require("../controllers/munInvestment.controller");
const regProdValController = require("../controllers/regProdVal.controller");
const munProdValController = require("../controllers/munProdVal.controller");
const regPurchasesController = require("../controllers/regPurchases.controller");
const munPurchasesController = require("../controllers/munPurchases.controller");
const regRemunerationController = require("../controllers/regRemuneration.controller");
const munRemunerationController = require("../controllers/munRemuneration.controller");
const regCostsController = require("../controllers/regCosts.controller");
const munCostsController = require("../controllers/munCosts.controller");
const regIntConsumptionController = require("../controllers/regIntConsumption.controller");
const munIntConsumptionController = require("../controllers/munIntConsumption.controller");
const regEmployeesGenderController = require("../controllers/regEmployeesGender.controller");

router.get("/getRegBrunva", regBrunvaController.getRegBrunva);
router.get("/getPayGender", payGenderController.getPayGender);
router.get("/getValAdded", valAddedController.getValAdded);
router.get("/getMunBrunva", munBrunvaController.getMunBrunva);
router.get("/getMunValAdded", munValAddedController.getMunValAdded);
router.get("/getMunPayGender", munPayGenderController.getMunPayGender);
router.get("/getRegEmployees", regEmployeesController.getRegEmployees);
router.get("/getMunEmployees", munEmployeesController.getMunEmployees);
router.get("/getRegEmployed", regEmployedController.getRegEmployed);
router.get("/getMunEmployed", munEmployedController.getMunEmployed);
router.get("/getRegResale", regResaleController.getRegResale);
router.get("/getMunResale", munResaleController.getMunResale);
router.get("/getRegInvestment", regInvestmentController.getRegInvestment);
router.get("/getMunInvestment", munInvestmentController.getMunInvestment);
router.get("/getRegProdVal", regProdValController.getRegProdVal);
router.get("/getMunProdVal", munProdValController.getMunProdVal);
router.get("/getRegPurchases", regPurchasesController.getRegPurchases);
router.get("/getMunPurchases", munPurchasesController.getMunPurchases);
router.get("/getRegRemuneration", regRemunerationController.getRegRemuneration);
router.get("/getMunRemuneration", munRemunerationController.getMunRemuneration);
router.get("/getRegCosts", regCostsController.getRegCosts);
router.get("/getMunCosts", munCostsController.getMunCosts);
router.get("/getRegIntConsumption", regIntConsumptionController.getRegIntConsumption);
router.get("/getMunIntConsumption", munIntConsumptionController.getMunIntConsumption);
router.get("/getRegEmployeesGender", regEmployeesGenderController.getRegEmployeesGender);

module.exports = router;
